### PR TITLE
Admin onboarding flow

### PR DESCRIPTION
**Pull request by evie-adenoyin**

### CODE REVIEW

**Review by slimsolz — COMMENTED** [review]
The layout is still not fixed @evie-adenoyin

**Comment by evie-adenoyin** [comment]
I have checked on my different devices and everything seems good... A screenshot would help, thanks

**Comment by slimsolz** [comment]
> I have checked on my different devices and everything seems good... A screenshot would help, thanks

Screenshot 2023-02-19 at 06 12 20

**Comment by evie-adenoyin** [comment]
I only get such a display when i zoom out to about 67% of my browers screen...

**Pull request closed without merging**
